// Generates src/icons.js from scripts/icon-manifest.mjs.
// Run: node scripts/gen-icons.mjs
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { ICONS } from './icon-manifest.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Build a glyph → [icon names] index to find SAFE (unambiguous) auto-replacements.
const glyphIcons = new Map();
for (const it of ICONS) for (const g of it.glyphs) {
  (glyphIcons.get(g) || glyphIcons.set(g, []).get(g)).push(it);
}

const auto = [];   // [glyph, iconName]  — safe to find-replace
const manual = []; // glyph — appears on a shared/multi icon; hand-map per site
for (const [g, list] of glyphIcons) {
  if (list.length === 1 && !list[0].shared) auto.push([g, list[0].name]);
  else manual.push(g);
}

const ch = c => `\\u${c.toString(16).toUpperCase().padStart(4, '0')}`;

let out = `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/gen-icons.mjs from scripts/icon-manifest.mjs.
// Do NOT edit by hand — edit the manifest and re-run \`node scripts/gen-icons.mjs\`.
//
// ICON.<name> is a single Private-Use-Area character rendered by the
// 'BrimstoneIcons' font (assets/fonts/brimstone-icons.woff2). It is monochrome
// and inherits CSS \`color\` in the DOM and \`fillStyle\` in canvas/3D.
// ─────────────────────────────────────────────────────────────────────────────

export const ICON = Object.freeze({
${ICONS.map(it => `  ${it.name}: '${ch(it.code)}',`).join('\n')}
});

// Glyphs that map to exactly ONE icon and are safe to replace mechanically.
// (Overloaded glyphs are intentionally excluded — they are hand-mapped per call
//  site to the correct semantic ICON. See the manifest \`note\` fields.)
export const EMOJI_TO_ICON = Object.freeze({
${auto.map(([g, n]) => `  '${g}': ICON.${n},`).join('\n')}
});

// The font-family to apply (DOM: \`font-family: var(--font-icons)\`; canvas:
// \`ctx.font = '<size> BrimstoneIcons'\`).
export const ICON_FONT_FAMILY = 'BrimstoneIcons';
`;

writeFileSync(join(root, 'src/icons.js'), out);

// Coverage report to stderr so the build is auditable.
console.error(`Generated src/icons.js`);
console.error(`  icons:            ${ICONS.length}`);
console.error(`  auto-replaceable: ${auto.length} glyphs`);
console.error(`  hand-mapped:      ${manual.length} glyphs (${manual.join(' ')})`);
const noArt = ICONS.filter(i => !i.gi);
if (noArt.length) console.error(`  MISSING art id:   ${noArt.map(i => i.name).join(', ')}`);
