// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/gen-icons.mjs from scripts/icon-manifest.mjs.
// Do NOT edit by hand — edit the manifest and re-run `node scripts/gen-icons.mjs`.
//
// ICON.<name> is a single Private-Use-Area character rendered by the
// 'BrimstoneIcons' font (assets/fonts/brimstone-icons.woff2). It is monochrome
// and inherits CSS `color` in the DOM and `fillStyle` in canvas/3D.
// ─────────────────────────────────────────────────────────────────────────────

export const ICON = Object.freeze({
  hero: '\uE000',
  witch: '\uE001',
  survivor: '\uE002',
  soldier: '\uE003',
  minion: '\uE004',
  zombie: '\uE005',
  woodGolem: '\uE006',
  ironGolem: '\uE007',
  captain: '\uE008',
  necromancer: '\uE009',
  rogue: '\uE00A',
  ogre: '\uE00B',
  person: '\uE00C',
  skeleton: '\uE00D',
  wood: '\uE010',
  metal: '\uE011',
  food: '\uE012',
  silver: '\uE013',
  scripture: '\uE014',
  herb: '\uE015',
  backpack: '\uE016',
  dawn: '\uE020',
  day: '\uE021',
  dusk: '\uE022',
  night: '\uE023',
  newMoon: '\uE024',
  townhall: '\uE030',
  inn: '\uE031',
  church: '\uE032',
  blacksmith: '\uE033',
  graveyard: '\uE034',
  dock: '\uE035',
  barn: '\uE036',
  watchtower: '\uE037',
  apothecary: '\uE038',
  stable: '\uE039',
  storehouse: '\uE03A',
  fort: '\uE03B',
  shelter: '\uE03C',
  mill: '\uE03D',
  sword: '\uE0A2',
  dagger: '\uE040',
  axe: '\uE041',
  shield: '\uE042',
  bow: '\uE043',
  gun: '\uE044',
  sling: '\uE045',
  staff: '\uE046',
  warhammer: '\uE047',
  horse: '\uE048',
  horn: '\uE049',
  grass: '\uE050',
  forest: '\uE051',
  dirt: '\uE052',
  rock: '\uE053',
  road: '\uE054',
  river: '\uE055',
  bridge: '\uE056',
  bleed: '\uE060',
  target: '\uE061',
  sparkle: '\uE062',
  water: '\uE063',
  stun: '\uE064',
  slow: '\uE065',
  fire: '\uE066',
  candle: '\uE067',
  eye: '\uE068',
  poison: '\uE069',
  wind: '\uE0B3',
  coffin: '\uE0B4',
  hourglass: '\uE0B5',
  timer: '\uE0B6',
  pause: '\uE0B7',
  play: '\uE0B8',
  close: '\uE070',
  check: '\uE071',
  menu: '\uE072',
  arrowRight: '\uE073',
  star: '\uE074',
  fit: '\uE075',
  soundOn: '\uE076',
  soundOff: '\uE077',
  planning: '\uE078',
  chronicle: '\uE079',
  missionLog: '\uE07A',
  conversation: '\uE07B',
  pin: '\uE07C',
  unpin: '\uE07D',
  book: '\uE07E',
  bot: '\uE07F',
  players: '\uE080',
  lock: '\uE081',
  invite: '\uE082',
  warning: '\uE083',
  balance: '\uE084',
  speedCine: '\uE085',
  speedFast: '\uE086',
  speedVfast: '\uE087',
  heartFull: '\uE088',
  heartEmpty: '\uE089',
  medical: '\uE08A',
  fatigue: '\uE08B',
  unarmed: '\uE08C',
  brimstone: '\uE08D',
  hexNode: '\uE08E',
  sentTo: '\uE08F',
  receivedFrom: '\uE090',
  join: '\uE091',
  off: '\uE092',
  lunge: '\uE093',
  seed: '\uE094',
  splash: '\uE095',
  crush: '\uE096',
  defeat: '\uE097',
  golem: '\uE098',
  nodeHero: '\uE099',
  nodeWitch: '\uE09A',
  nodeNeutral: '\uE09B',
  checkbox: '\uE09C',
  heartbreak: '\uE09D',
  battle: '\uE09E',
  reward: '\uE09F',
  supplies: '\uE0A0',
  gear: '\uE0A1',
  pentacle: '\uE0B0',
  flag: '\uE0B1',
  wardShield: '\uE0B2',
});

// Glyphs that map to exactly ONE icon and are safe to replace mechanically.
// (Overloaded glyphs are intentionally excluded — they are hand-mapped per call
//  site to the correct semantic ICON. See the manifest `note` fields.)
export const EMOJI_TO_ICON = Object.freeze({
  '♟': ICON.soldier,
  '☥': ICON.necromancer,
  '👹': ICON.ogre,
  '🧑': ICON.person,
  '🍞': ICON.food,
  '🍖': ICON.food,
  '🥈': ICON.silver,
  '🪙': ICON.silver,
  '🎒': ICON.backpack,
  '🌅': ICON.dawn,
  '☀': ICON.day,
  '🌇': ICON.dusk,
  '🌙': ICON.night,
  '🌑': ICON.newMoon,
  '🌒': ICON.newMoon,
  '🏛': ICON.townhall,
  '🏨': ICON.inn,
  '⛪': ICON.church,
  '🪦': ICON.graveyard,
  '⚓': ICON.dock,
  '🗼': ICON.watchtower,
  '🐎': ICON.stable,
  '🏰': ICON.fort,
  '🏠': ICON.shelter,
  '🪓': ICON.axe,
  '🏹': ICON.bow,
  '🔫': ICON.gun,
  '🐴': ICON.horse,
  '📯': ICON.horn,
  '🌲': ICON.forest,
  '🛤': ICON.road,
  '🌉': ICON.bridge,
  '🩸': ICON.bleed,
  '✨': ICON.sparkle,
  '💫': ICON.stun,
  '🐌': ICON.slow,
  '🔥': ICON.fire,
  '👁': ICON.eye,
  '💨': ICON.wind,
  '⚰': ICON.coffin,
  '⏳': ICON.hourglass,
  '⏱': ICON.timer,
  '⏸': ICON.pause,
  '▶': ICON.play,
  '✕': ICON.close,
  '✓': ICON.check,
  '☰': ICON.menu,
  '➤': ICON.arrowRight,
  '★': ICON.star,
  '⛶': ICON.fit,
  '🔊': ICON.soundOn,
  '🔇': ICON.soundOff,
  '📋': ICON.planning,
  '🗒': ICON.missionLog,
  '💬': ICON.conversation,
  '📌': ICON.pin,
  '📎': ICON.unpin,
  '📖': ICON.book,
  '🤖': ICON.bot,
  '👥': ICON.players,
  '🔒': ICON.lock,
  '✉': ICON.invite,
  '⚠': ICON.warning,
  '⚖': ICON.balance,
  '🎬': ICON.speedCine,
  '⏩': ICON.speedFast,
  '⏭': ICON.speedVfast,
  '♥': ICON.heartFull,
  '♡': ICON.heartEmpty,
  '⚕': ICON.medical,
  '😓': ICON.fatigue,
  '👊': ICON.unarmed,
  '🜂': ICON.brimstone,
  '⬡': ICON.hexNode,
  '📤': ICON.sentTo,
  '📥': ICON.receivedFrom,
  '⚡': ICON.join,
  '🚫': ICON.off,
  '🤺': ICON.lunge,
  '🌱': ICON.seed,
  '💢': ICON.splash,
  '💥': ICON.crush,
  '💀': ICON.defeat,
  '🗿': ICON.golem,
  '🔵': ICON.nodeHero,
  '🔴': ICON.nodeWitch,
  '⭕': ICON.nodeNeutral,
  '☐': ICON.checkbox,
  '💔': ICON.heartbreak,
  '⛧': ICON.pentacle,
  '⚑': ICON.flag,
});

// The font-family to apply (DOM: `font-family: var(--font-icons)`; canvas:
// `ctx.font = '<size> BrimstoneIcons'`).
export const ICON_FONT_FAMILY = 'BrimstoneIcons';

// ─────────────────────────────────────────────────────────────────────────────
// Resource icon colorization
//
// The BrimstoneIcons glyphs are monochrome and inherit CSS `color`. By default a
// resource glyph takes the surrounding text color; these helpers tint each
// resource by type so wood reads brown, herbs green, etc., consistently across
// every player-facing render site.
//
// Two ways to colorize:
//   • DOM/HTML — wrap the glyph in `coloredResourceIcon(id)` (a span carrying the
//     `.res-icon`/`.res-icon--<id>` classes; colors live in styles.css), or use
//     `coloredResourceLabel(id, label)` to tint just the leading glyph of a label
//     string while leaving the trailing text on the ambient color.
//   • Canvas/other — read the hex straight from `RESOURCE_ICON_COLOR[id]`.
// ─────────────────────────────────────────────────────────────────────────────

// Canonical resource ids (matches ResourceType values in tiles.js). Kept local
// so icons.js stays dependency-free (no tiles.js import → no import cycle).
export const RESOURCE_ICON_COLOR = Object.freeze({
  wood:      '#b07a45', // warm timber brown
  metal:     '#9aa6b2', // cold steel grey-blue
  food:      '#e0883a', // warm ration orange
  silver:    '#cfd6dd', // bright silvery white
  scripture: '#d8b25c', // aged parchment / gilt
  herbs:     '#6fbf73', // living-green herb
  herb:      '#6fbf73', // alias (ICON name is `herb`, ResourceType is `herbs`)
});

// Glyph (PUA char) → resource id, so a bare label glyph can be located + tinted.
const RES_GLYPH_TO_ID = Object.freeze({
  [ICON.wood]:      'wood',
  [ICON.metal]:     'metal',
  [ICON.food]:      'food',
  [ICON.silver]:    'silver',
  [ICON.scripture]: 'scripture',
  [ICON.herb]:      'herbs',
});

/** True when `id` is one of the six tintable resource types. */
export function isResourceId(id) {
  return Object.prototype.hasOwnProperty.call(RESOURCE_ICON_COLOR, id);
}

/**
 * Return the resource glyph for `id` wrapped in a tinted span (HTML string).
 * Falls back to the bare glyph (no span) for unknown ids so callers can pass it
 * through safely. `glyph` overrides the looked-up glyph when supplied.
 */
export function coloredResourceIcon(id, glyph) {
  const ch = glyph ?? ICON[id === 'herbs' ? 'herb' : id];
  if (!ch) return '';
  if (!isResourceId(id)) return ch;
  return `<span class="res-icon res-icon--${id}">${ch}</span>`;
}

/**
 * Tint just the leading resource glyph of a label string (e.g. RESOURCE_LABEL
 * values like " Herbs") and leave the trailing text on the ambient color.
 * If the string doesn't start with a known resource glyph it is returned
 * unchanged, so this is safe to apply blindly to any label.
 */
export function coloredResourceLabel(label) {
  if (typeof label !== 'string' || !label) return label;
  const id = RES_GLYPH_TO_ID[label.charAt(0)];
  if (!id) return label;
  return `<span class="res-icon res-icon--${id}">${label.charAt(0)}</span>${label.slice(1)}`;
}

// Matches any of the six resource glyphs (U+E010 wood .. U+E015 herb) wherever
// they sit in a string. (Range covers wood/metal/food/silver/scripture/herb.)
const RES_GLYPH_RE = /[\uE010-\uE015]/g;

/**
 * Tint EVERY resource glyph found anywhere in an HTML string (not just a
 * leading one). Use when the glyph may sit mid-string (e.g. "Use  Herbs").
 * Returns HTML — never pass the result into an attribute value.
 */
export function tintResourceGlyphs(html) {
  if (typeof html !== 'string' || !html) return html;
  return html.replace(RES_GLYPH_RE, (ch) => {
    const id = RES_GLYPH_TO_ID[ch];
    return id ? `<span class="res-icon res-icon--${id}">${ch}</span>` : ch;
  });
}

/**
 * Resource tint hex for a single character, or `null` if `ch` isn't a tintable
 * resource glyph. The canvas analogue of `coloredResourceIcon` — instead of a
 * `<span>` (no HTML on a 2D canvas) the caller reads the hex and sets
 * `ctx.fillStyle` directly. Returns `null` for ambient text so callers can
 * fall back to their default fill color.
 */
export function resourceColorForGlyph(ch) {
  const id = RES_GLYPH_TO_ID[ch];
  return id ? RESOURCE_ICON_COLOR[id] : null;
}

/**
 * Split a floater string (e.g. `"+ Wood"`) into ordered segments, each
 * `{ text, color }`. A run of resource glyphs gets that resource's hex tint;
 * everything else gets `color: null` (ambient — caller paints it in its own
 * default fill). Mirrors the HTML UI, where only the glyph is tinted and the
 * label stays on the surrounding color. The concatenation of segment `text`
 * always equals the input, so a caller that ignores `color` reproduces the
 * original string verbatim. Adjacent glyphs of the SAME color are coalesced
 * into one segment so the canvas paint loop draws fewer pieces.
 *
 * @param {string} text
 * @returns {{text:string,color:(string|null)}[]}
 */
export function splitColoredFloaterSegments(text) {
  if (typeof text !== 'string' || !text) return [];
  const segments = [];
  let buf = '';
  let bufColor = null;
  for (const ch of text) {
    const color = resourceColorForGlyph(ch);
    if (color !== bufColor) {
      if (buf) segments.push({ text: buf, color: bufColor });
      buf = ch;
      bufColor = color;
    } else {
      buf += ch;
    }
  }
  if (buf) segments.push({ text: buf, color: bufColor });
  return segments;
}
